Update EF, refactor QA.Core.Data
QuantumArt/QA.Core pull request #2
Opened 2017-08-04 12:02 UTC by movchinnikov

QA.Core.Data.QP.ContentResult.cs
Рекомендации
1. Совмещает в себе возможность "почти безопасно" манипулировать проперти Contents, но при этом предоставляет возможность прочитать, а еще хуже установить его. 
Предлагаю 
а.перевести проперти в поле.
б. инициировать поле в конструкторе
в. пометить его readonly
2. В качестве Contents используется обычный словарь, но при этом с ним производятся операции чтения и установки. Теоритически это может привести к ненужным исключениям.
Предлагаю перевести Contents в ConcurrentDictionary

QA.Core.Data.QP.IQpContentItem
Именование как будто объект, а на самом деле сервис. Предлагаю переименовать в IQpContentItemService
Каждый метод принимает в качестве параметра IQpDbConnector, это не очень корректно. 
Предлагаю
если это синглтон (и/или смарт) подключение инициировать его в сервисе
если п1 неприменим, то подготивить эксштеншионы для IQpDbConnector

QA.Core.Data.QP.QPContentManager.cs
метод GetIncludes - почему Get, если возвращает void?
есть в нем такой кусок кода:
...
var attr = attributes.SingleOrDefault(w => w.Name == path);
var contentName = DbConnection.GetContentName(attr.RelatedContentId.Value);

var values = string.Empty;

if (attr.LinkId == null)
...

если attr будет null, то получим стремное исключение NullReferenceException. надо обработать и сделать правильное поведение
если attr быть null не может, то использовать стоит Single, тогда если attr не будет найдет, то сразу можно увидеть где именно не нашлось требуемого объекта
 

Прошу обратить особое внимание на методы Fields в классе QPContentManager.cs, как мне кажется исправлена потеря полей при вызове Fields и Include. если это не так - прошу сообщить

2017-08-04 14:05 UTC, karlovnv commented
Данный API хоть и написан, но никогда и нигде не использовался.
Поэтому переименование не повлечет последствий. Однако, в будущем следует с осторожностью изменять публичные методы или свойства, а также избегать изменений, не имеющих обратной совместимости.

Совет: Для манипуляций над статьями лучше использовать не данный API, а Quantumart.QP8.BLL или использовать маппинг контентов в Linq2SQL или EF6. 

Класс ContentResult не является ThreadSafe, и не рассчитан на использование в нескольких потоках, влекущие изменение состояния. Поэтому Использовать CuncurrentDictionary

2017-08-09 11:28 UTC, CelutP requested changes
Необходимо исправить конфликт

2017-08-09 12:16 UTC, CelutP commented on QA.Core.Data/QP/QPContentManager.cs
> +            Query.Fields = $"{Query.Fields},{string.Join(",", FieldList)}";
Зачем менять поведение?

2017-09-15 15:24 UTC, CelutP commented
Меняется QA.Core.Data, а инкрементируется версия почему-то у QA.Core.Service

2017-12-12 14:13 UTC, closed without merging